### PR TITLE
First-pass at improving template system.

### LINKED ISSUE #135: Emails are not encoded properly
If alert summary and/or description contains non-ascii symbols, it breaks emails.

* There is no content type headers in email and most of mail clients don't use UTF-8 by default - the message body is broken in most of mail clients.
* If non-ascii symbols will end up in email subject, it's even worse. All headers (including subject) need to be encoded properly and if they are not, various sanity checks in mail transport (including virus and spam scanners) could throw these mails away. For example Amavis complains here:

``BAD HEADER Non-encoded 8-bit data (char C3 hex) in message header 'Subject'``

### PR DESCRIPTION
**Pull request by brian-brazil**
- Cut back to bare minimum to make the rest simpler
- Consistency in config naming
- Have one data strucutre that's the same for all templates
- Pass in common labels to templates
- Support templates almost everywhere
- Support multiple SMTP recipients
- Support non-ASCII SMTP headers
- Handle colour logic via templates
- Make $subjects have consistent output, go maps aren't sorted.
- Make tests pass when v6 is disabled

@fabxc 

Fixes #135 #126 #74 

Still needs improvement, but this should be a good base.

### CODE REVIEW

File: config/notifies.go [hunk 1]
```diff
@@ -15,62 +15,50 @@ package config
...
 	"fmt"
+	"strings"
 )
 
 var (
 	// DefaultHipchatConfig defines default values for Hipchat configurations.
 	DefaultHipchatConfig = HipchatConfig{
-		ColorFiring:   "purple",
-		ColorResolved: "green",
+		Color:         `{{ if eq .Status "firing" }}purple{{ else }}green{{ end }}`,
```
Comment (fabxc) [inline config/notifies.go]: This is the mix of template files and inlined templating I'm not yet sure about.
Then again, this is one of a bunch of configs taken from the old implementation that are not backed by an implementation.

Maybe it makes sense to remove these as well to start unbiased by the old structure when adding new integrations.

File: config/notifies.go [hunk 2]
```diff
@@ -15,62 +15,50 @@ package config
...
-
-		Templates: SlackTemplates{
-			Title:     "slack.default.title",
-			TitleLink: "slack.default.title_link",
-			Pretext:   "slack.default.pretext",
-			Text:      "slack.default.text",
-			Fallback:  "slack.default.fallback",
-		},
+		Color:     `{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}`,
+		Title:     `{{template "slack.default.title" . }}`,
```
Comment (fabxc) [inline config/notifies.go]: I see where you are going.
I actually like this approach – it's a clean way to mix between inlining and files.

File: notify/impl.go [hunk 3]
```diff
@@ -62,6 +66,79 @@ func Build(confs []*config.Receiver, tmpl *template.Template) map[string]Fanout
...
 const contentTypeJSON = "application/json"
 
+// End-users should not be exposed to Go's type system,
+// as this will confuse them and prevent simple things like
+// simple equality checks to fail. Map everything to float64/string.
+type templateData struct {
+	Status                      string
+	Alerts                      []templateAlert
+	AlertCommonLabels           map[string]string
+	AlertCommonLabelnamesSorted []string
```
Comment (fabxc) [inline notify/impl.go]: The `Sorted` suffix just seems noisy. That can be part of the documentation. As the user has no influence on iteration order anyway the info is not helping much anyway.

File: notify/impl.go [hunk 4]
```diff
@@ -62,6 +66,79 @@ func Build(confs []*config.Receiver, tmpl *template.Template) map[string]Fanout
 
 const contentTypeJSON = "application/json"
 
+// End-users should not be exposed to Go's type system,
```
Comment (fabxc) [inline notify/impl.go]: I agree that the `model.LabelName`/`model.LabelValue` types do not need to be exposed. Don't agree with the statement in general though, e.g. in Prometheus templating, I don't think dates and such should be plain strings.

Lots of infrastructure software is written in Go. Most of them (Docker, Kubernetes) allow accessing data by defining templates. Anyone making use of such features can be expected to be able to deal with the well-defined template system.

File: notify/impl.go [hunk 5]
```diff
@@ -62,6 +66,79 @@ func Build(confs []*config.Receiver, tmpl *template.Template) map[string]Fanout
...
+// as this will confuse them and prevent simple things like
+// simple equality checks to fail. Map everything to float64/string.
+type templateData struct {
+	Status                      string
+	Alerts                      []templateAlert
```
Comment (fabxc) [inline notify/impl.go]: I would export both types for visibility in the godoc.
This should remain `model.Alerts` in my opinion – of course then labels are no longer strings and such.

I wonder how this would even come up if everything consistently is `model.LabelName` though. Comparisons would work with each other and string literals.
I cannot immediately see rich use-cases that would cause much trouble here.

File: notify/impl.go [hunk 6]
```diff
@@ -183,11 +262,32 @@ func (n *Email) Notify(ctx context.Context, as ...*types.Alert) error {
...
+		return fmt.Errorf("error executing from template: %s", err)
 	}
-	if err := c.Rcpt(n.conf.Email); err != nil {
-		return err
+	addrs, err := mail.ParseAddressList(from)
+	if err != nil {
+		return fmt.Errorf("error parsing from addresses: %s", err)
+	}
+	if len(addrs) != 1 {
+		return fmt.Errorf("error, must be exactly one from address")
```
Comment (fabxc) [inline notify/impl.go]: No need to prefix this with error if it's not required to make it a readable statement.

File: notify/impl.go [hunk 7]
```diff
@@ -62,6 +66,79 @@ func Build(confs []*config.Receiver, tmpl *template.Template) map[string]Fanout
...
+	GroupLabels                 map[string]string
+	GroupLabelnamesSorted       []string
+}
+
+type templateAlert struct {
+	Labels      map[string]string
+	Annotations map[string]string
+}
+
+func generateTemplateData(ctx context.Context, as ...*types.Alert) *templateData {
```
Comment (fabxc) [inline notify/impl.go]: Summing up the above, I'm not sure about this whole mapping here. I would like to see some use cases causing trouble exposing the original types/data structures with their potentially useful methods.

File: config/notifies.go (hunk 1 above)
Comment (brian-brazil) [inline config/notifies.go]: I'm okay with kicking this one down to the default.tmpl. For things this brief I was thinking it may make sense to do it inline.

There's a few other equivalents that can be replaced by an if in templates, mostly color related.

File: notify/impl.go [hunk 8]
```diff
@@ -268,34 +363,25 @@ func (n *PagerDuty) Notify(ctx context.Context, as ...*types.Alert) error {
...
 		return s
 	}
+	details := make(map[string]string, len(n.conf.Details))
+	for k, v := range n.conf.Details {
+		details[k] = tmpl(v)
+	}
 
 	msg := &pagerDutyMessage{
-		ServiceKey:  n.conf.ServiceKey,
+		ServiceKey:  tmpl(n.conf.ServiceKey),
```
Comment (fabxc) [inline notify/impl.go]: What's the use case here? Just having the service key in a different file?

File: template/template.go [hunk 9]
```diff
@@ -49,140 +41,33 @@ func FromGlobs(paths ...string) (*Template, error) {
...
+	err = tmpl.Execute(&buf, data)
 	return buf.String(), err
 }
 
-func (t *Template) ExecuteText(w io.Writer, name string, data interface{}) error {
-	return t.text.ExecuteTemplate(w, name, data)
-}
-
-func (t *Template) ExecuteHTMLString(name string, data interface{}) (string, error) {
+func (t *Template) ExecuteHTMLString(html string, data interface{}) (string, error) {
```
Comment (fabxc) [inline template/template.go]: Compiling the templates on each execution is an anti-pattern in my opinion. Even though we have it in Prometheus too. Templates are compilable for a reason.

Not feeling very strongly, but I also see it as an advantage to avoid races and as a result broken notifications.
I don't see much benefit to be constantly able to change the templates – it happens to rarely that sending a `SIGHUP` is not too much overhead.

File: test/acceptance.go [hunk 10]
```diff
@@ -86,7 +86,7 @@ func NewAcceptanceTest(t *testing.T, opts *AcceptanceOpts) *AcceptanceTest {
 func freeAddress() string {
 	// Let the OS allocate a free address, close it and hope
 	// it is still free when starting Alertmanager.
-	l, err := net.Listen("tcp", ":0")
+	l, err := net.Listen("tcp4", ":0")
```
Comment (fabxc) [inline test/acceptance.go]: What was the issue with the version-free one?

**Comment by fabxc** [comment]
Needs rebase.

File: notify/impl.go (hunk 4 above)
Comment (brian-brazil) [inline notify/impl.go]: > I don't think dates and such should be plain strings.

Timestamps are currently float64 in Prometheus templates, the alertmanager doesn't expose any dates yet. I can see us exposing some though for alert starting time, so for consistency we'd be looking at float64 and a humanize function there.

> Anyone making use of such features can be expected to be able to deal with the well-defined template system.

I don't think this is a reasonable expectation. Go's templating is designed for use by the same people writing the code, who will obviously already be familiar with Go's type system and have control of the surrounding code to handle anything that comes up.

What we're doing here is different as we're exposing Go's template system to users who in general will have no knowledge of Go, and may not even know what a type system is. I think losing a handful of minor utility functions is a small price to make things more easily understandable by our whole userbase.

File: config/notifies.go (hunk 1 above)
Comment (fabxc) [inline config/notifies.go]: Actually fine with that. This was just the first one I saw. But it's consistent what is happening in other places below :+1:

File: notify/impl.go (hunk 3 above)
Comment (brian-brazil) [inline notify/impl.go]: Removed.

> I guess you want it to allow in-order iteration over the maps

Yip.

File: notify/impl.go (hunk 5 above)
Comment (brian-brazil) [inline notify/impl.go]: > I would export both types for visibility in the godoc.

Done.

> I cannot immediately see rich use-cases that would cause much trouble here.

I can imagine users wanting to compare the labelname with the labelvalue, and also across with annotations.

The more common things that'll break will be string functions, they can only take in one type.

File: notify/impl.go (hunk 6 above)
Comment (brian-brazil) [inline notify/impl.go]: Done

File: notify/impl.go (hunk 8 above)
Comment (brian-brazil) [inline notify/impl.go]: I can imagine routing being plumbed through from service discovery. I had a system many years back that used this technique very successfully for email, and can see the same being done for pagerduty etc.

File: template/template.go (hunk 9 above)
Comment (brian-brazil) [inline template/template.go]: You'll need to send a SIGHUP anyway as they're coming from the config. As mentioned on IRC this is just a first pass, ultimately they should be compiled at the config load stage both for efficiency and to catch syntax errors earlier.

File: test/acceptance.go (hunk 10 above)
Comment (brian-brazil) [inline test/acceptance.go]: Breaks if you've disabled v6 on your Linux machine, such as I have on my entire home network.

**Comment by brian-brazil** [comment]
> Needs rebase.

I've already done so, I suspect you accidentally `--forced` over #144 so the datadir change is coming up again.

File: notify/impl.go (hunk 8 above)
Comment (fabxc) [inline notify/impl.go]: I see :+1:

File: template/template.go (hunk 9 above)
Comment (fabxc) [inline template/template.go]: :+1:

File: test/acceptance.go (hunk 10 above)
Comment (fabxc) [inline test/acceptance.go]: I always understood this version-less format to chose any working one – okay then.

Comment (fabxc) [inline test/acceptance.go]: Actually, the normal stdlib `ListenAndServe()` function, which is essentially used everywhere also uses [this](https://golang.org/src/net/http/server.go#L1868).

Accordingly none of our tools serving HTTP content should work for you then – confused.

Comment (brian-brazil) [inline test/acceptance.go]: As far as I can tell it's when the test tries to connect to `[::1]` that things break.

Comment (fabxc) [inline test/acceptance.go]: I guess with a normal port it defaults to ipv4 and with :0 to ipv6 then or something – doesn't matter.

File: notify/impl.go [hunk 11]
```diff
@@ -62,6 +66,85 @@ func Build(confs []*config.Receiver, tmpl *template.Template) map[string]Fanout
...
 
+// TemplateData is the data passed to notification templates.
+// End-users should not be exposed to Go's type system,
+// as this will confuse them and prevent simple things like
+// simple equality checks to fail. Map everything to float64/string.
+type TemplateData struct {
+	Status            string
+	Alerts            []TemplateAlert
+	AlertCommonLabels map[string]string
+
```
Comment (fabxc) [inline notify/impl.go]: You don't see any use for common annotations? Both suffer from the problem of changing as more alerts are sorted into the group. But if for example `summary` is common across all of them, that can be useful for some templates.

Comment (brian-brazil) [inline notify/impl.go]: I don't think the use case is as strong as for labels, I can see potential use but only in a similar way to what I'm doing to subject which won't tend to have space to fit a summary. I figure a wait and see approach is best, we can always add it in later.

**Comment by fabxc** [comment]
Okay, let's merge so we have the base in place :ship:
