### PR TITLE
config: validate URLs at config load time

### LINKED ISSUE #1460: Alertmanager fails to create slack posts, if channel name contains spaces
**What did you do?**

Configured ``channel`` in ``slack_configs`` with name ``Team ABC``:

    receivers:
      - name: team-abc
        slack_configs:
          - api_url: <webhook to Mattermost>
            channel: 'Team ABC'

**What did you expect to see?**

message posted in Mattermost channel "Team ABC".

**What did you see instead? Under which circumstances?**

No message in Mattermost, instead errors in Alertmanager logs:

    level=error ts=2018-07-08T21:25:12.077586206Z caller=dispatch.go:279 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 404"

**Environment**

(using docker image ``prom/alertmanager:v0.15.0``, running in OpenShift)

* System information:

	  $ uname -srm
	  Linux 3.10.0-693.21.1.el7.x86_64 x86_64

* Alertmanager version:

	  $ alertmanager --version
	  alertmanager, version 0.15.0 (branch: HEAD, revision: 462c969d85cf1a473587754d55e4a3c4a2abc63c)
	    build user:       root@bec9939eb862
	    build date:       20180622-11:58:41
	    go version:       go1.10.3

### PR DESCRIPTION
**Pull request by simonpasquier**
Closes #1460

### CODE REVIEW

File: config/config_test.go [hunk 1]
```diff
@@ -292,6 +293,98 @@ func TestJSONMarshalSecret(t *testing.T) {
...
+	}
+	// u003c -> "<"
+	// u003e -> ">"
+	require.Equal(t, "\"\\u003csecret\\u003e\"", string(c), "SecretURL not properly elided in JSON.")
+
+	c, err = yaml.Marshal(u)
+	if err != nil {
+		t.Fatal(err)
+	}
+	require.Equal(t, "<secret>\n", string(c), "SecretURL not properly elidedin YAML.")
```
Comment (brian-brazil) [inline config/config_test.go]: missing space

File: notify/impl.go [hunk 2]
```diff
@@ -759,8 +763,10 @@ func (n *Hipchat) Notify(ctx context.Context, as ...*types.Alert) (bool, error)
 		data     = n.tmpl.Data(receiverName(ctx, n.logger), groupLabels(ctx, n.logger), as...)
 		tmplText = tmplText(n.tmpl, data, &err)
 		tmplHTML = tmplHTML(n.tmpl, data, &err)
-		url      = fmt.Sprintf("%sv2/room/%s/notification?auth_token=%s", n.conf.APIURL, n.conf.RoomID, n.conf.AuthToken)
+		// n.conf.APIURL is already checked at configuration load time.
+		url, _ = url.Parse(n.conf.APIURL.String())
```
Comment (mxinden) [inline notify/impl.go]: I am a bit confused here, why not just `n.conf.APIURL` is this not already a URL?

Comment (simonpasquier) [reply notify/impl.go]: `n.conf.APIURL` is a pointer so I didn't want to modify it.

**Comment by mxinden** [comment]
@simonpasquier There are a couple more [`URL` `string`s](https://github.com/simonpasquier/alertmanager/blob/f736014b0fe1e7da45823ea8e57bd8fd72bdc621/config/notifiers.go#L482) inside `notifier.go`. Would it make sense to replace them as well?

**Comment by simonpasquier** [comment]
@mxinden absolutely! Not sure how I managed to miss them...

**Comment by brian-brazil** [comment]
The pushover url is a template, not a url.

**Comment by simonpasquier** [comment]
@brian-brazil yep, I replied too fast. This isn't the Pushover API URL...

File: notify/impl.go (hunk 2 above)
Comment (stuartnelson3) [reply notify/impl.go]: you could also do

```go
u := *c.conf.APIURL
u.Path += fmt.Sprintf("v2/room/%s/notification?auth_token=%s", n.conf.RoomID, n.conf.AuthToken)
// ...
resp, err := ctxhttp.Post(ctx, c, u.String(), contentTypeJSON, &buf)
```

Comment (stuartnelson3) [reply notify/impl.go]: since we've assigned something to variable name `url`, we've shadowed the reference to the package `net/url` in this scope. Having url's named `u` is annoying, but at some point someone will want to use `net/url` later in this package..

File: notify/impl.go [hunk 3]
```diff
@@ -802,8 +802,7 @@ func (n *Hipchat) Notify(ctx context.Context, as ...*types.Alert) (bool, error)
 		tmplText = tmplText(n.tmpl, data, &err)
 		tmplHTML = tmplHTML(n.tmpl, data, &err)
 		roomid   = tmplText(n.conf.RoomID)
-		// n.conf.APIURL is already checked at configuration load time.
-		url, _ = url.Parse(n.conf.APIURL.String())
+		url      = *n.conf.APIURL
```
Comment (simonpasquier) [inline notify/impl.go]: This isn't a deep copy, needs to be fixed.

File: notify/impl.go [hunk 4]
```diff
@@ -798,8 +802,9 @@ func (n *Hipchat) Notify(ctx context.Context, as ...*types.Alert) (bool, error)
 		tmplText = tmplText(n.tmpl, data, &err)
 		tmplHTML = tmplHTML(n.tmpl, data, &err)
 		roomid   = tmplText(n.conf.RoomID)
-		url      = fmt.Sprintf("%sv2/room/%s/notification?auth_token=%s", n.conf.APIURL, roomid, n.conf.AuthToken)
+		apiURL   = *n.conf.APIURL
```
Comment (simonpasquier) [inline notify/impl.go]: This isn't a deep copy, needs to be fixed.
