### PR TITLE
Fix resolve notifications

### LINKED ISSUE #611: Alertmanager sends the resolved messages continuously
This problem is totally same as this closed issue: https://github.com/prometheus/alertmanager/issues/246

I changed the `resolve_timeout` parameter as you suggested but it did not help.

### PR DESCRIPTION
**Pull request by brancz**
This PR introduces a fundamental change to the protobufs gossiped, because the previously optimization we implemented for the 0.5 release did not turn out to work as expected. Instead we now gossip the entire list of previously firing and resolved alerts, so if the currently firing alerts are a subset of the alerts that were firing at the last notification, then we can deduplicate. It works the same way for resolved notifications, if the currently resolved alerts are a subset of those that have already been notified about then they are deduplcated. Consequently, if currently firing or resolved alerts are not a subset of the previous sets, then they need to be notified about (after the `group_interval`). This means the payload that is gossiped increases significantly, however, I decided against a premature optimization and rather benchmark this implementation if a load problem actually comes up.

I wanted to get this out for people to test, who have been struggling with this issue for a while. As this is quite a fundamental change and touches most of the critical parts of the notification pipeline I would like to test this a bit before having it ready to merge. /cc @ddewaele @tsboj17 @mattbostock

Fixes #611 and #598 

@fabxc @stuartnelson3 @mxinden

### CODE REVIEW

File: notify/notify.go [hunk 1]
```diff
@@ -382,55 +382,47 @@ func (ws *WaitStage) Exec(ctx context.Context, alerts ...*types.Alert) (context.
...
-		binary.BigEndian.PutUint64(b, uint64(a.Fingerprint()))
-		// Resolved status is part of the identity.
-		if a.Resolved() {
-			b[8] = 1
-		}
-		for i, b := range sha256.Sum256(b) {
-			xsum[i] ^= b
-		}
+func hashAlert(a *types.Alert) uint64 {
+	b := make([]byte, 0, 1024)
```
Comment (fabxc) [inline notify/notify.go]: Can we get that one from a sync.Pool? Prometheus doesn't have it because mostly it does shortcut around the hash. (We probably still want to add it there eventually as well though as the QE hashes a lot.)

File: notify/notify.go [hunk 2]
```diff
@@ -442,14 +434,18 @@ func allAlertsResolved(alerts []*types.Alert) bool {
 	return true
 }
 
-func (n *DedupStage) needsUpdate(entry *nflogpb.Entry, hash []byte, resolved bool, repeat time.Duration) (bool, error) {
+func (n *DedupStage) needsUpdate(entry *nflogpb.Entry, firing, resolved map[uint64]struct{}, repeat time.Duration) (bool, error) {
 	// If we haven't notified about the alert group before, notify right away
 	// unless we only have resolved alerts.
 	if entry == nil {
-		return !resolved, nil
+		return ((len(firing) > 0) || (n.sendResolved && len(resolved) > 0)), nil
```
Comment (fabxc) [inline notify/notify.go]: Wondering here. I remember providing explicit logic about not sending resolved notifications about stuff we have never notified about being firing in the first place.

But maybe just keep as it is here – might be better in doubt in case some other AM notified something as firing but couldn't propagate the entry via the mesh and then died.

File: notify/notify.go [hunk 3]
```diff
@@ -476,10 +472,16 @@ func (n *DedupStage) Exec(ctx context.Context, alerts ...*types.Alert) (context.
 		return ctx, nil, fmt.Errorf("repeat interval missing")
 	}
 
-	hash := n.hash(alerts)
-	resolved := n.resolved(alerts)
+	firing := map[uint64]struct{}{}
+	resolved := map[uint64]struct{}{}
 
-	ctx = WithNotificationHash(ctx, hash)
```
Comment (fabxc) [inline notify/notify.go]: This context entry is completely gone now. The related function and const should be removed as well.

But we are redoing the whole hashing we have done before. Wouldn't it make sense to pass the hashes through the context to the SetNotifies stage?

File: notify/notify_test.go [hunk 4]
```diff
@@ -91,44 +86,44 @@ func TestDedupStageNeedsUpdate(t *testing.T) {
...
-			res:   true,
+			entry:        nil,
+			firingAlerts: map[uint64]struct{}{2: struct{}{}, 3: struct{}{}, 4: struct{}{}},
+			res:          true,
 		}, {
-			entry: &nflogpb.Entry{GroupHash: []byte{1, 2, 3}},
-			hash:  []byte{2, 3, 4},
-			res:   true,
+			entry:        &nflogpb.Entry{FiringAlerts: []uint64{1, 2, 3}},
+			firingAlerts: map[uint64]struct{}{2: struct{}{}, 3: struct{}{}, 4: struct{}{}},
```
Comment (fabxc) [inline notify/notify_test.go]: Add a small constructor function (inlined in the test function or elsewhere) to construct those sets? Probably cannot hurt overall to make a `alertHashSet` helper type hiding the awkwardness of `map[uint64]struct{}`.

File: notify/notify_test.go [hunk 5]
```diff
@@ -181,35 +184,41 @@ func TestDedupStage(t *testing.T) {
...
 	ctx, res, err = s.Exec(ctx, alerts...)
 	require.Contains(t, err.Error(), "result size")
 
 	// Must return no error and no alerts no need to update.
+	i = 0
 	s.nflog = &testNflog{
 		qerr: nflog.ErrNotFound,
+		qres: []*nflogpb.Entry{
+			{
+				FiringAlerts: []uint64{uint64(0), uint64(1), uint64(2)},
```
Comment (fabxc) [inline notify/notify_test.go]: The explicit `uint64()`s here should not be necessary.

File: nflog/nflogpb/set.go [hunk 6]
```diff
@@ -0,0 +1,30 @@
+package nflogpb
```
Comment (brancz) [inline nflog/nflogpb/set.go]: Only reason I'm making this a separate file is so it doesn't get overridden when regenerating from the proto.

File: notify/notify.go [hunk 7]
```diff
@@ -382,55 +382,47 @@ func (ws *WaitStage) Exec(ctx context.Context, alerts ...*types.Alert) (context.
...
+
+	for labelName, _ := range a.Labels {
+		labelNames = append(labelNames, labelName)
 	}
-	return xsum[:]
+	sort.Sort(labelNames)
+
+	for _, labelName := range labelNames {
+		b = append(b, string(labelName)...)
+		b = append(b, sep)
```
Comment (brancz) [inline notify/notify.go]: done

**Comment by brancz** [comment]
Applied all your comments @fabxc. Care for a re-review? :slightly_smiling_face:

**Comment by fabxc** [comment]
Currently pondering with releasing it now or waiting a bit more to try to get in a first version of the new UI. I suppose you prefer the fix sooner?

In general, nothing speaks against two releases in short proximity.

**Comment by stuartnelson3** [comment]
I vote for getting the fix out, and then we just make another release when the UI is ready. Last release was back in November, and there have been many additions since then.

**Comment by mattbostock** [comment]
@fabxc Sooner rather than later would be appreciated as this bug has the potential to create a lot of noise.

#717 (solving #609) is also an important fix, though I think the current implementation may preclude backporting it.

**Comment by mattbostock** [comment]
Looks like this is included in 0.6.0 though not mentioned in the release description or the CHANGELOG:
https://github.com/prometheus/alertmanager/releases/tag/v0.6.0

Thanks!

**Comment by damomurf** [comment]
Is it actually included in the 0.6.0 release? I'm seeing an infinitely firing "resolved" alert on 0.6.1?

**Comment by fabxc** [comment]
@damomurf can you describe the scenario more precisely? Those things are hard to debug without a detailed timeline of when alerts were flowing in and what the exact notification behavior was.

A reproducible scenario is ideal, of course.

**Comment by damomurf** [comment]
Sure @fabxc, I appreciate it's difficult to solve without being able to reproduce.

So currently, I have an "alert resolved" message being fired to Slack every three hours. The actual alert was resolved days ago and if I visit current alerts in either AlertManager or Prometheus, they're both empty.

`[RESOLVED] ElasticSearchClusterStatus account (/monitoring/es-exporter hostnane:port marathon-discovery-aws mesos-monitor)`

**Comment by fabxc** [comment]
I assume 3 hours is your configured repeat interval. Restarting the AMs should solve it (but is not a viable solution obviously), will try to reproduce it later but it sounds like some edge case that went wrong and it could be hard to hit it manually again.

**Comment by damomurf** [comment]
That's correct, 3 hours is the timeout. This is a single instance of Alertmanager, if that helps?
