### PR TITLE
Fix flaky test TestClusterJoinAndReconnect/TestTLSConnection again (#3278)

### LINKED ISSUE #3287: TestClusterJoinAndReconnect/TestJoinLeave flake
Per https://app.circleci.com/pipelines/github/prometheus/alertmanager/3414/workflows/c8f0b621-4406-438c-96ee-be09c7a45d92/jobs/15139 seems to be flaky but really hard to reproduce.

It took me a few retries before I saw it failing:

```
🙇 -> go test -run "TestClusterJoinAndReconnect/TestJoinLeave" -count 300
--- FAIL: TestClusterJoinAndReconnect (0.02s)
    --- FAIL: TestClusterJoinAndReconnect/TestJoinLeave (0.00s)
        cluster_test.go:104: 
                Error Trace:    /Users/gotjosh/go/src/github.com/prometheus/alertmanager/cluster/cluster_test.go:104
                Error:          Not equal: 
                                expected: 2
                                actual  : 1
                Test:           TestClusterJoinAndReconnect/TestJoinLeave
FAIL
exit status 1
FAIL    github.com/prometheus/alertmanager/cluster      249.449s
```

### PR DESCRIPTION
**Pull request by SoloJacobs**
_Repeating my commit message for convenience:_

Two commits have already merged in order to address the flakiness of this test.
However, I can still reproduce the issue using:
```sh
go test -failfast -run "TestClusterJoinAndReconnect/TestJoinLeave" -count 600 ./cluster
```
An easy way to increase the failure rate is to increase CPU load, e.g.,
```sh
yes > /dev/null &; yes > /dev/null &; yes > /dev/null &; yes > /dev/null &
```
On my machine the combination of these commands fails every time.
The underlying reason for the failure is that the test only waits for `p2` to be ready, but this does not reflect whether `p` has updated its memberlist.

Edit due to the comments I got: <s>We can ensure that `p` has updated its memberlist by waiting for `NotifyJoin` to be called. The test is now slightly slower, 0.8 seconds on my machine.</s> The test now retries the assertions in question using `Eventually`.

_Side-note_

I am new to the project and feedback is very appreciated. It was hard to find something that avoids spin looping and does not change the API of `Peer`. Also, the `WaitReady` and `Settle` calls are redundant now, since we are actually waiting for `NotifyJoin`. But leaving them in does not hurt either.

Fixes #3287

### CODE REVIEW

**Comment by SoloJacobs** [comment]
@gotjosh I think you can review  this best.

File: cluster/cluster.go [hunk 1]
```diff
@@ -82,6 +82,10 @@ type Peer struct {
 	peerJoinCounter            prometheus.Counter
 
 	logger *slog.Logger
+
+	// This allows inspecting leave and join events in a unit testing context.
+	notifyJoinTest  func(n *memberlist.Node)
+	notifyLeaveTest func(n *memberlist.Node)
```
Comment (siavashs) [inline cluster/cluster.go]: Please don't add test related logic into runtime code.

File: cluster/cluster_test.go [hunk 2]
```diff
@@ -100,9 +105,11 @@ func testJoinLeave(t *testing.T) {
 	require.NoError(t, err)
 	go p2.Settle(context.Background(), 0*time.Second)
 	require.NoError(t, p2.WaitReady(context.Background()))
+	require.Equal(t, p2.Self().Name, <-chJoin)
```
Comment (siavashs) [inline cluster/cluster_test.go]: Just use `require.Eventually()`, see other examples in the project.

Comment (SoloJacobs) [reply cluster/cluster_test.go]: Done

File: cluster/cluster.go (hunk 1 above)
Comment (SoloJacobs) [reply cluster/cluster.go]: I guess the trade-off here is between: simple runtime code vs. having a more deterministic test. Both solutions seem acceptable to me, so I have opted for the suggestion.

**Comment by sysadmind** [comment]
I don't think that this resolved all of the flaky tests. https://github.com/prometheus/alertmanager/actions/runs/19104722659/job/54585342806

**Comment by SoloJacobs** [comment]
@sysadmind That seems very likely, I didn't play around with `TestSetPeerNames`.  I will follow-up with a commit to apply the change to all the tests in `cluster_test.go`.
